# Generated by Django 2.1.5 on 2019-04-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190408_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='image1',
            field=models.ImageField(blank=True, upload_to='blog_images', verbose_name='second image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, upload_to='blog_images', verbose_name='third image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image3',
            field=models.ImageField(blank=True, upload_to='blog_images', verbose_name='fourth image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image4',
            field=models.ImageField(blank=True, upload_to='blog_images', verbose_name='fifth image'),
        ),
    ]
