# Generated by Django 2.1.5 on 2019-04-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='question',
        ),
    ]
